language: node_js
node_js:
  - '0.8'
  - '0.9'
  - '0.10'
rvm:
  - '1.9.3'
  - '2.0.0'
before_install:
  - 'npm install -g bower'
  - 'gem install bundler'
before_script:
  - 'npm install -g grunt-cli'
