# Base Jekyll configuration

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile. There is also a
# _config.build.yml to set custom overrides for `grunt build`.


# Project configs
# ===========================

name: jpress
title: JPress
subtitle: A Jekyll Boilerplate for blogs and pages
description: 'A Jekyll Boilerplate for blog and pages'
# Used on opengraph protocol and twitter cards
image:
url: http://getjpress.com


# Jekyll configs
# ===========================

# The number should be the maximum number of Posts
# you’d like to be displayed per- page in the generated site.
paginate: 1

# Page path style
paginate_path: '/blog/page/:num'

# If publishing to a subdirectory as in http://site.com/project set '/project'
# else leave it empty. Remember to change 'baseurl' on '_config.build.yml'
# before run the build task
baseurl:

# If publishing your assets to a subdirectory as
# in http://site.com/project/assets/js/app.js set '/assets'
# else leave it empty.
# JPress will append this to all url assets.
# E.g. /css/app.css -> baseurl + assetsurl + /css/app.css
assetsurl: /assets

# Destination folder, dont forget to change on Gruntfile.js too!
destination: ./dist

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['image', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /blog/:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Markdown library
markdown: redcarpet

# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Use Pygments to highlight code blocks
pygments: true


# JPress configs
# ===========================

# Enable titlecase. e.g. 'This is an awesome post' -> 'This is an Awesome Post'
titlecase: true

# Enable OpenGraph tags
open_graph: true

# Facebook
facebook_insights: '100000504340213'

# Google
google_webmaster: 'DpD9oer8uLmd-1PoX5r7BIBWeC8-ehyz16ZxZXwzA7c'
google_analitycs: 'UA-35822150-1'

# Disqus Comments, if `disquis_short_name` is empty comments will be disabled.
disqus_short_name:

# Disqus Comments, if `share_this` is empty share component will be disabled.
share_this:


# Author configs
# ===========================

author:
  name: Oswaldo Acauan
  email: oswaldoacauan@gmail.com
  github: oswaldoacauan
  twitter: oswaldoacauan # If twitter is not empty, twitter cards will be enabled
  gplus: 118319269143668101211
