# Base Jekyll configuration

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile. There is also a
# _config.build.yml to set custom overrides for `grunt build`.


# Blog configs
# ===========================

name: oswaldoacauan.github.io
title: Oswaldo Acauan
subtitle:
description: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptates, dolorum, nisi itaque debitis maiores voluptatum vitae saepe quae ipsa cupiditate aspernatur expedita quam molestias nostrum magnam cum earum minus temporibus.'
# Used on opengraph protocol and twitter cards
image:
baseurl: /
url: http://oswaldoacauan.com


# Jekyll configs
# ===========================

# With safe mode enabled any plugin will work
safe: false

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /

# Source folder
source: .

# Destination folder
destination: ./dist

# Plugins folder
# plugins: ./_plugins

# Layouts folder
layouts: ./_layouts

# Exclude directories and/or files from the conversion.
# Grunt moves image files and asset directories.
exclude: ['image', 'css', 'js', 'fonts',
          '**.png', '**.jpg', '**.jpeg', '**.gif', '**.webp', '**.svg', '**.ico']

# Force inclusion of directories and/or files in the conversion.
# .htaccess is a good example since dotfiles are excluded by default.
include: ['.htaccess']

# Default post path style
# date  /:categories/:year/:month/:day/:title.html
# pretty  /:categories/:year/:month/:day/:title/
# none  /:categories/:title.html
permalink: /:title/

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Markdown library
markdown: redcarpet

# Markdown library options
# redcarpet:
  # extensions: ['fenced_code_blocks', 'smart']

# Use Pygments to highlight code blocks
pygments: true



# Jekyll plugins configs
# ===========================

pages: ./_pages

# Social configs
# ===========================

# Facebook
facebook_insights: '100000504340213'

# Google
google_webmaster: 'DpD9oer8uLmd-1PoX5r7BIBWeC8-ehyz16ZxZXwzA7c'
google_analitycs: 'UA-35822150-1'

# Disqus Comments
disqus_short_name:


# Author configs
# ===========================

author:
  name: Oswaldo Acauan
  email: oswaldoacauan@gmail.com
  github: oswaldoacauan
  twitter: oswaldoacauan
  gplus: 118319269143668101211
