# Build Jekyll configuration
# These settings override _config.yml on `grunt build`

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false

# If publishing to a subdirectory as in http://site.com/project set '/project'
# else leave it empty. Remember to change 'baseurl' on '_config.build.yml'
# before run the build task
# baseurl: /blog

# If publishing your assets to a subdirectory as
# in http://site.com/project/assets/js/app.js set '/assets'
# else leave it empty.
assetsurl: /assets
